### ISSUE TITLE
Change profile path

### ISSUE THREAD

**Issue by zzhmark** [Crawler995/wtcolor#2]
My current profile path is:
` $env:LocalAppData\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`

Can you make it clear how to change the path? 

I tried choosing a color theme, but the prompt would just get stuck on the message:
`Open config file failed! Please check the given path.`

I also tried putting the path as an argument for `wtcolor`, but nothing changed.

**Comment by Crawler995** [comment]
I am so sorry. I've found that the bug incurs because of a version update of Windows Terminal which modifies the default profile path, and honestly there's some logical error and magic code in my program, so a infinite loop will incur. I have to apologize that I have no time to fix it currently.
You can go to the [repo](https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/windowsterminal) to copy the color theme config to Windows Terminal config file manually in order to change the color scheme. Before it, you can preview the scheme in their README.md.
So sorry for this.

**Comment by zzhmark** [comment]
谢谢回复！你的工具挺实在的，网上一个一个翻毕竟挺麻烦，也不容易看效果。

我觉得还可以加一些改背景图片和opacity等参数的功能，有空的话你做做看吧。

:+1: :+1:
